
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AppToast: typeof import("../components/AppToast.vue")['default']
export const CfConfirmModal: typeof import("../components/CfConfirmModal.vue")['default']
export const GoalMiniPie: typeof import("../components/GoalMiniPie.vue")['default']
export const PatientAvatar: typeof import("../components/PatientAvatar.vue")['default']
export const PatientBrandMark: typeof import("../components/PatientBrandMark.vue")['default']
export const PatientHeader: typeof import("../components/PatientHeader.vue")['default']
export const PatientLoadingLogo: typeof import("../components/PatientLoadingLogo.vue")['default']
export const PatientMealPlanGate: typeof import("../components/PatientMealPlanGate.vue")['default']
export const PatientMealPlanUploadOverlay: typeof import("../components/PatientMealPlanUploadOverlay.vue")['default']
export const PatientMenuDrawer: typeof import("../components/PatientMenuDrawer.vue")['default']
export const PatientNavigationLoader: typeof import("../components/PatientNavigationLoader.vue")['default']
export const PatientNotificationsPanel: typeof import("../components/PatientNotificationsPanel.vue")['default']
export const PatientPageSkeleton: typeof import("../components/PatientPageSkeleton.vue")['default']
export const PatientPdfViewer: typeof import("../components/PatientPdfViewer.vue")['default']
export const PatientPushSettings: typeof import("../components/PatientPushSettings.vue")['default']
export const PatientPwaPrompt: typeof import("../components/PatientPwaPrompt.vue")['default']
export const PatientPwaUpdate: typeof import("../components/PatientPwaUpdate.vue")['default']
export const PatientSkeleton: typeof import("../components/PatientSkeleton.vue")['default']
export const PatientTabBar: typeof import("../components/PatientTabBar.vue")['default']
export const PlayerHeader: typeof import("../components/PlayerHeader.vue")['default']
export const PlayerNavigation: typeof import("../components/PlayerNavigation.vue")['default']
export const BellaActionSheet: typeof import("../components/bella/BellaActionSheet.vue")['default']
export const BellaDailyDiaryBar: typeof import("../components/bella/DailyDiaryBar.vue")['default']
export const BellaFoodSearchPicker: typeof import("../components/bella/FoodSearchPicker.vue")['default']
export const BellaMealConfirmModal: typeof import("../components/bella/MealConfirmModal.vue")['default']
export const BellaMealPhotoGuideSheet: typeof import("../components/bella/MealPhotoGuideSheet.vue")['default']
export const BellaMealSlotPicker: typeof import("../components/bella/MealSlotPicker.vue")['default']
export const BellaPhotoGuideTipIcon: typeof import("../components/bella/PhotoGuideTipIcon.vue")['default']
export const BellaRestaurantIntentButtons: typeof import("../components/bella/RestaurantIntentButtons.vue")['default']
export const BellaSwapButtons: typeof import("../components/bella/SwapButtons.vue")['default']
export const BibliotecaScrollRow: typeof import("../components/biblioteca/BibliotecaScrollRow.vue")['default']
export const CheckinFridayPrompt: typeof import("../components/checkin/CheckinFridayPrompt.vue")['default']
export const CheckinTemplateEditorPreview: typeof import("../components/checkin/CheckinTemplateEditorPreview.vue")['default']
export const CheckinTypeformFlow: typeof import("../components/checkin/CheckinTypeformFlow.vue")['default']
export const CheckinFoodMoodPicker: typeof import("../components/checkin/FoodMoodPicker.vue")['default']
export const CheckinNotoEmojiLottie: typeof import("../components/checkin/NotoEmojiLottie.client.vue")['default']
export const CommunityFeed: typeof import("../components/community/CommunityFeed.vue")['default']
export const CoursesAulaPlayerIcons: typeof import("../components/courses/AulaPlayerIcons.vue")['default']
export const CoursesCourseVideoPlayer: typeof import("../components/courses/CourseVideoPlayer.vue")['default']
export const CoursesFlorescerPlayerIcons: typeof import("../components/courses/FlorescerPlayerIcons.vue")['default']
export const CoursesLessonFormModal: typeof import("../components/courses/LessonFormModal.vue")['default']
export const CoursesLessonNotesPanel: typeof import("../components/courses/LessonNotesPanel.vue")['default']
export const CoursesLessonSummaryContent: typeof import("../components/courses/LessonSummaryContent.vue")['default']
export const CoursesLessonSummaryPanel: typeof import("../components/courses/LessonSummaryPanel.vue")['default']
export const CoursesLessonTranscriptionPanel: typeof import("../components/courses/LessonTranscriptionPanel.vue")['default']
export const CoursesVideoUploadQueuePanel: typeof import("../components/courses/VideoUploadQueuePanel.vue")['default']
export const DietaCheckIcon: typeof import("../components/dieta/CheckIcon.vue")['default']
export const DietaMealPlanUploadCard: typeof import("../components/dieta/MealPlanUploadCard.vue")['default']
export const DietaMealSubstitutionsModal: typeof import("../components/dieta/MealSubstitutionsModal.vue")['default']
export const EvolucaoExerciseArm: typeof import("../components/evolucao/ExerciseArm.vue")['default']
export const EvolucaoFoodPlate: typeof import("../components/evolucao/FoodPlate.vue")['default']
export const EvolucaoGoalsPanel: typeof import("../components/evolucao/GoalsPanel.vue")['default']
export const EvolucaoNutritionMonthView: typeof import("../components/evolucao/NutritionMonthView.vue")['default']
export const EvolucaoSleepChart: typeof import("../components/evolucao/SleepChart.vue")['default']
export const EvolucaoWaterBottle: typeof import("../components/evolucao/WaterBottle.vue")['default']
export const EvolucaoWeightPanel: typeof import("../components/evolucao/WeightPanel.vue")['default']
export const HomeCurrentMealCard: typeof import("../components/home/CurrentMealCard.vue")['default']
export const HomeJourneyMacroRing: typeof import("../components/home/JourneyMacroRing.vue")['default']
export const HomeMacroBar: typeof import("../components/home/MacroBar.vue")['default']
export const HomeMacroPizzaRing: typeof import("../components/home/MacroPizzaRing.vue")['default']
export const HomeNutritionPanel: typeof import("../components/home/NutritionPanel.vue")['default']
export const HomeNutritionStatCarousel: typeof import("../components/home/NutritionStatCarousel.vue")['default']
export const OnboardingHeightPicker: typeof import("../components/onboarding/OnboardingHeightPicker.vue")['default']
export const OnboardingOptionCard: typeof import("../components/onboarding/OnboardingOptionCard.vue")['default']
export const OnboardingShell: typeof import("../components/onboarding/OnboardingShell.vue")['default']
export const PatientsPatientGoalsPanel: typeof import("../components/patients/PatientGoalsPanel.vue")['default']
export const PatientsPatientNutritionSection: typeof import("../components/patients/PatientNutritionSection.vue")['default']
export const PatientsPatientPhotosPanel: typeof import("../components/patients/PatientPhotosPanel.vue")['default']
export const SharedCfDateInput: typeof import("../components/shared/CfDateInput.vue")['default']
export const SharedCfDateTimeInput: typeof import("../components/shared/CfDateTimeInput.vue")['default']
export const SharedCfPhoneInput: typeof import("../components/shared/CfPhoneInput.vue")['default']
export const SharedCfSelect: typeof import("../components/shared/CfSelect.vue")['default']
export const SharedCfTileActionsMenu: typeof import("../components/shared/CfTileActionsMenu.vue")['default']
export const SharedCfTileCarousel: typeof import("../components/shared/CfTileCarousel.vue")['default']
export const SharedWeightRulerPicker: typeof import("../components/shared/WeightRulerPicker.vue")['default']
export const WhatsappBusinessProfileModal: typeof import("../components/whatsapp/BusinessProfileModal.vue")['default']
export const WhatsappChatBody: typeof import("../components/whatsapp/ChatBody.vue")['default']
export const WhatsappChatFooter: typeof import("../components/whatsapp/ChatFooter.vue")['default']
export const WhatsappChatHeader: typeof import("../components/whatsapp/ChatHeader.vue")['default']
export const WhatsappChatMessageActionsPanel: typeof import("../components/whatsapp/ChatMessageActionsPanel.vue")['default']
export const WhatsappChatSidebar: typeof import("../components/whatsapp/ChatSidebar.vue")['default']
export const WhatsappCreateGroupModal: typeof import("../components/whatsapp/CreateGroupModal.vue")['default']
export const WhatsappDocumentViewerModal: typeof import("../components/whatsapp/DocumentViewerModal.vue")['default']
export const WhatsappGroupInfoModal: typeof import("../components/whatsapp/GroupInfoModal.vue")['default']
export const WhatsappGroupMediaDocsModal: typeof import("../components/whatsapp/GroupMediaDocsModal.vue")['default']
export const WhatsappGroupMessageList: typeof import("../components/whatsapp/GroupMessageList.vue")['default']
export const WhatsappGroupPickerModal: typeof import("../components/whatsapp/GroupPickerModal.vue")['default']
export const WhatsappInteractiveButtonsBuilder: typeof import("../components/whatsapp/InteractiveButtonsBuilder.vue")['default']
export const WhatsappInteractiveCarouselBuilder: typeof import("../components/whatsapp/InteractiveCarouselBuilder.vue")['default']
export const WhatsappInteractiveListBuilder: typeof import("../components/whatsapp/InteractiveListBuilder.vue")['default']
export const WhatsappInteractiveMessagePreview: typeof import("../components/whatsapp/InteractiveMessagePreview.vue")['default']
export const WhatsappInteractivePreviewSideModal: typeof import("../components/whatsapp/InteractivePreviewSideModal.vue")['default']
export const WhatsappMediaComposerModal: typeof import("../components/whatsapp/MediaComposerModal.vue")['default']
export const WhatsappPollComposerModal: typeof import("../components/whatsapp/PollComposerModal.vue")['default']
export const WhatsappPrivateMessageList: typeof import("../components/whatsapp/PrivateMessageList.vue")['default']
export const WhatsappSaveContactModal: typeof import("../components/whatsapp/SaveContactModal.vue")['default']
export const WhatsappSendContactsModal: typeof import("../components/whatsapp/SendContactsModal.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const VitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const PwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const PwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const PwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const PwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const PwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAppToast: LazyComponent<typeof import("../components/AppToast.vue")['default']>
export const LazyCfConfirmModal: LazyComponent<typeof import("../components/CfConfirmModal.vue")['default']>
export const LazyGoalMiniPie: LazyComponent<typeof import("../components/GoalMiniPie.vue")['default']>
export const LazyPatientAvatar: LazyComponent<typeof import("../components/PatientAvatar.vue")['default']>
export const LazyPatientBrandMark: LazyComponent<typeof import("../components/PatientBrandMark.vue")['default']>
export const LazyPatientHeader: LazyComponent<typeof import("../components/PatientHeader.vue")['default']>
export const LazyPatientLoadingLogo: LazyComponent<typeof import("../components/PatientLoadingLogo.vue")['default']>
export const LazyPatientMealPlanGate: LazyComponent<typeof import("../components/PatientMealPlanGate.vue")['default']>
export const LazyPatientMealPlanUploadOverlay: LazyComponent<typeof import("../components/PatientMealPlanUploadOverlay.vue")['default']>
export const LazyPatientMenuDrawer: LazyComponent<typeof import("../components/PatientMenuDrawer.vue")['default']>
export const LazyPatientNavigationLoader: LazyComponent<typeof import("../components/PatientNavigationLoader.vue")['default']>
export const LazyPatientNotificationsPanel: LazyComponent<typeof import("../components/PatientNotificationsPanel.vue")['default']>
export const LazyPatientPageSkeleton: LazyComponent<typeof import("../components/PatientPageSkeleton.vue")['default']>
export const LazyPatientPdfViewer: LazyComponent<typeof import("../components/PatientPdfViewer.vue")['default']>
export const LazyPatientPushSettings: LazyComponent<typeof import("../components/PatientPushSettings.vue")['default']>
export const LazyPatientPwaPrompt: LazyComponent<typeof import("../components/PatientPwaPrompt.vue")['default']>
export const LazyPatientPwaUpdate: LazyComponent<typeof import("../components/PatientPwaUpdate.vue")['default']>
export const LazyPatientSkeleton: LazyComponent<typeof import("../components/PatientSkeleton.vue")['default']>
export const LazyPatientTabBar: LazyComponent<typeof import("../components/PatientTabBar.vue")['default']>
export const LazyPlayerHeader: LazyComponent<typeof import("../components/PlayerHeader.vue")['default']>
export const LazyPlayerNavigation: LazyComponent<typeof import("../components/PlayerNavigation.vue")['default']>
export const LazyBellaActionSheet: LazyComponent<typeof import("../components/bella/BellaActionSheet.vue")['default']>
export const LazyBellaDailyDiaryBar: LazyComponent<typeof import("../components/bella/DailyDiaryBar.vue")['default']>
export const LazyBellaFoodSearchPicker: LazyComponent<typeof import("../components/bella/FoodSearchPicker.vue")['default']>
export const LazyBellaMealConfirmModal: LazyComponent<typeof import("../components/bella/MealConfirmModal.vue")['default']>
export const LazyBellaMealPhotoGuideSheet: LazyComponent<typeof import("../components/bella/MealPhotoGuideSheet.vue")['default']>
export const LazyBellaMealSlotPicker: LazyComponent<typeof import("../components/bella/MealSlotPicker.vue")['default']>
export const LazyBellaPhotoGuideTipIcon: LazyComponent<typeof import("../components/bella/PhotoGuideTipIcon.vue")['default']>
export const LazyBellaRestaurantIntentButtons: LazyComponent<typeof import("../components/bella/RestaurantIntentButtons.vue")['default']>
export const LazyBellaSwapButtons: LazyComponent<typeof import("../components/bella/SwapButtons.vue")['default']>
export const LazyBibliotecaScrollRow: LazyComponent<typeof import("../components/biblioteca/BibliotecaScrollRow.vue")['default']>
export const LazyCheckinFridayPrompt: LazyComponent<typeof import("../components/checkin/CheckinFridayPrompt.vue")['default']>
export const LazyCheckinTemplateEditorPreview: LazyComponent<typeof import("../components/checkin/CheckinTemplateEditorPreview.vue")['default']>
export const LazyCheckinTypeformFlow: LazyComponent<typeof import("../components/checkin/CheckinTypeformFlow.vue")['default']>
export const LazyCheckinFoodMoodPicker: LazyComponent<typeof import("../components/checkin/FoodMoodPicker.vue")['default']>
export const LazyCheckinNotoEmojiLottie: LazyComponent<typeof import("../components/checkin/NotoEmojiLottie.client.vue")['default']>
export const LazyCommunityFeed: LazyComponent<typeof import("../components/community/CommunityFeed.vue")['default']>
export const LazyCoursesAulaPlayerIcons: LazyComponent<typeof import("../components/courses/AulaPlayerIcons.vue")['default']>
export const LazyCoursesCourseVideoPlayer: LazyComponent<typeof import("../components/courses/CourseVideoPlayer.vue")['default']>
export const LazyCoursesFlorescerPlayerIcons: LazyComponent<typeof import("../components/courses/FlorescerPlayerIcons.vue")['default']>
export const LazyCoursesLessonFormModal: LazyComponent<typeof import("../components/courses/LessonFormModal.vue")['default']>
export const LazyCoursesLessonNotesPanel: LazyComponent<typeof import("../components/courses/LessonNotesPanel.vue")['default']>
export const LazyCoursesLessonSummaryContent: LazyComponent<typeof import("../components/courses/LessonSummaryContent.vue")['default']>
export const LazyCoursesLessonSummaryPanel: LazyComponent<typeof import("../components/courses/LessonSummaryPanel.vue")['default']>
export const LazyCoursesLessonTranscriptionPanel: LazyComponent<typeof import("../components/courses/LessonTranscriptionPanel.vue")['default']>
export const LazyCoursesVideoUploadQueuePanel: LazyComponent<typeof import("../components/courses/VideoUploadQueuePanel.vue")['default']>
export const LazyDietaCheckIcon: LazyComponent<typeof import("../components/dieta/CheckIcon.vue")['default']>
export const LazyDietaMealPlanUploadCard: LazyComponent<typeof import("../components/dieta/MealPlanUploadCard.vue")['default']>
export const LazyDietaMealSubstitutionsModal: LazyComponent<typeof import("../components/dieta/MealSubstitutionsModal.vue")['default']>
export const LazyEvolucaoExerciseArm: LazyComponent<typeof import("../components/evolucao/ExerciseArm.vue")['default']>
export const LazyEvolucaoFoodPlate: LazyComponent<typeof import("../components/evolucao/FoodPlate.vue")['default']>
export const LazyEvolucaoGoalsPanel: LazyComponent<typeof import("../components/evolucao/GoalsPanel.vue")['default']>
export const LazyEvolucaoNutritionMonthView: LazyComponent<typeof import("../components/evolucao/NutritionMonthView.vue")['default']>
export const LazyEvolucaoSleepChart: LazyComponent<typeof import("../components/evolucao/SleepChart.vue")['default']>
export const LazyEvolucaoWaterBottle: LazyComponent<typeof import("../components/evolucao/WaterBottle.vue")['default']>
export const LazyEvolucaoWeightPanel: LazyComponent<typeof import("../components/evolucao/WeightPanel.vue")['default']>
export const LazyHomeCurrentMealCard: LazyComponent<typeof import("../components/home/CurrentMealCard.vue")['default']>
export const LazyHomeJourneyMacroRing: LazyComponent<typeof import("../components/home/JourneyMacroRing.vue")['default']>
export const LazyHomeMacroBar: LazyComponent<typeof import("../components/home/MacroBar.vue")['default']>
export const LazyHomeMacroPizzaRing: LazyComponent<typeof import("../components/home/MacroPizzaRing.vue")['default']>
export const LazyHomeNutritionPanel: LazyComponent<typeof import("../components/home/NutritionPanel.vue")['default']>
export const LazyHomeNutritionStatCarousel: LazyComponent<typeof import("../components/home/NutritionStatCarousel.vue")['default']>
export const LazyOnboardingHeightPicker: LazyComponent<typeof import("../components/onboarding/OnboardingHeightPicker.vue")['default']>
export const LazyOnboardingOptionCard: LazyComponent<typeof import("../components/onboarding/OnboardingOptionCard.vue")['default']>
export const LazyOnboardingShell: LazyComponent<typeof import("../components/onboarding/OnboardingShell.vue")['default']>
export const LazyPatientsPatientGoalsPanel: LazyComponent<typeof import("../components/patients/PatientGoalsPanel.vue")['default']>
export const LazyPatientsPatientNutritionSection: LazyComponent<typeof import("../components/patients/PatientNutritionSection.vue")['default']>
export const LazyPatientsPatientPhotosPanel: LazyComponent<typeof import("../components/patients/PatientPhotosPanel.vue")['default']>
export const LazySharedCfDateInput: LazyComponent<typeof import("../components/shared/CfDateInput.vue")['default']>
export const LazySharedCfDateTimeInput: LazyComponent<typeof import("../components/shared/CfDateTimeInput.vue")['default']>
export const LazySharedCfPhoneInput: LazyComponent<typeof import("../components/shared/CfPhoneInput.vue")['default']>
export const LazySharedCfSelect: LazyComponent<typeof import("../components/shared/CfSelect.vue")['default']>
export const LazySharedCfTileActionsMenu: LazyComponent<typeof import("../components/shared/CfTileActionsMenu.vue")['default']>
export const LazySharedCfTileCarousel: LazyComponent<typeof import("../components/shared/CfTileCarousel.vue")['default']>
export const LazySharedWeightRulerPicker: LazyComponent<typeof import("../components/shared/WeightRulerPicker.vue")['default']>
export const LazyWhatsappBusinessProfileModal: LazyComponent<typeof import("../components/whatsapp/BusinessProfileModal.vue")['default']>
export const LazyWhatsappChatBody: LazyComponent<typeof import("../components/whatsapp/ChatBody.vue")['default']>
export const LazyWhatsappChatFooter: LazyComponent<typeof import("../components/whatsapp/ChatFooter.vue")['default']>
export const LazyWhatsappChatHeader: LazyComponent<typeof import("../components/whatsapp/ChatHeader.vue")['default']>
export const LazyWhatsappChatMessageActionsPanel: LazyComponent<typeof import("../components/whatsapp/ChatMessageActionsPanel.vue")['default']>
export const LazyWhatsappChatSidebar: LazyComponent<typeof import("../components/whatsapp/ChatSidebar.vue")['default']>
export const LazyWhatsappCreateGroupModal: LazyComponent<typeof import("../components/whatsapp/CreateGroupModal.vue")['default']>
export const LazyWhatsappDocumentViewerModal: LazyComponent<typeof import("../components/whatsapp/DocumentViewerModal.vue")['default']>
export const LazyWhatsappGroupInfoModal: LazyComponent<typeof import("../components/whatsapp/GroupInfoModal.vue")['default']>
export const LazyWhatsappGroupMediaDocsModal: LazyComponent<typeof import("../components/whatsapp/GroupMediaDocsModal.vue")['default']>
export const LazyWhatsappGroupMessageList: LazyComponent<typeof import("../components/whatsapp/GroupMessageList.vue")['default']>
export const LazyWhatsappGroupPickerModal: LazyComponent<typeof import("../components/whatsapp/GroupPickerModal.vue")['default']>
export const LazyWhatsappInteractiveButtonsBuilder: LazyComponent<typeof import("../components/whatsapp/InteractiveButtonsBuilder.vue")['default']>
export const LazyWhatsappInteractiveCarouselBuilder: LazyComponent<typeof import("../components/whatsapp/InteractiveCarouselBuilder.vue")['default']>
export const LazyWhatsappInteractiveListBuilder: LazyComponent<typeof import("../components/whatsapp/InteractiveListBuilder.vue")['default']>
export const LazyWhatsappInteractiveMessagePreview: LazyComponent<typeof import("../components/whatsapp/InteractiveMessagePreview.vue")['default']>
export const LazyWhatsappInteractivePreviewSideModal: LazyComponent<typeof import("../components/whatsapp/InteractivePreviewSideModal.vue")['default']>
export const LazyWhatsappMediaComposerModal: LazyComponent<typeof import("../components/whatsapp/MediaComposerModal.vue")['default']>
export const LazyWhatsappPollComposerModal: LazyComponent<typeof import("../components/whatsapp/PollComposerModal.vue")['default']>
export const LazyWhatsappPrivateMessageList: LazyComponent<typeof import("../components/whatsapp/PrivateMessageList.vue")['default']>
export const LazyWhatsappSaveContactModal: LazyComponent<typeof import("../components/whatsapp/SaveContactModal.vue")['default']>
export const LazyWhatsappSendContactsModal: LazyComponent<typeof import("../components/whatsapp/SendContactsModal.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyVitePwaManifest: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
export const LazyNuxtPwaManifest: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
export const LazyNuxtPwaAssets: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']>
export const LazyPwaAppleImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']>
export const LazyPwaAppleSplashScreenImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']>
export const LazyPwaFaviconImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']>
export const LazyPwaMaskableImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']>
export const LazyPwaTransparentImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
