export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta } from '../node_modules/nuxt/dist/pages/runtime/composables';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useApiBase } from '../composables/useApiBase';
export { useConfirm } from '../composables/useConfirm';
export { useDietaProgress } from '../composables/useDietaProgress';
export { useMealItemOverrides } from '../composables/useMealItemOverrides';
export { useMealPlan } from '../composables/useMealPlan';
export { useMealSubstitutions } from '../composables/useMealSubstitutions';
export { usePatientApp, PatientProfile } from '../composables/usePatientApp';
export { usePatientLocalTime } from '../composables/usePatientLocalTime';
export { usePatientMealPlan } from '../composables/usePatientMealPlan';
export { useTileActionsMenu, closeAllTileActionMenus } from '../composables/useTileActionsMenu';
export { getPatientScrollRoot, scrollPatientPageBy, useVerticalWheelPassthrough, usePatientHorizontalWheelBridge } from '../composables/useVerticalWheelPassthrough';
export { PROD_API_ORIGIN, PROD_API_BASE, PROD_WHATSAPP_API_BASE } from '../utils/api-env';
export { BELLA_ACTIONS, navigateBellaAction } from '../utils/bella-actions';
export { getMessageAttachment, getMessageDisplayText, shouldShowUserMessageText, getUserMessageImageUrl, formatBellaMarkdown } from '../utils/bella-message-format';
export { topicToTone, inferCourseTopic, countCourseLessons, formatModuleCount, formatLessonCount, mapCourseToTile, mapEbookToTile } from '../utils/course-tile';
export { fixWindowsVitePaths } from '../utils/fix-windows-vite-paths';
export { getPatientTimeZone, getLocalDateKey, getLocalTimeParts } from '../utils/local-date';
export { roundMacro, createMealItemId, createMealItem, normalizeItemFromAi, applyFoodMatch, scaleMealItem, sumMealItems, normalizeMealItemsForSave, mealTypeLabel } from '../utils/meal-diary';
export { splitMealItemDisplay } from '../utils/meal-item-display';
export { formatMealItemLabel, formatMealItemsLabels } from '../utils/meal-plan-format';
export { parseMealTimeToMinutes, getMealIdForTimeFromMeals } from '../utils/meal-plan-time';
export { DEV_MOBILE_API_BASE, DEV_PANEL_API_BASE, isLocalHostname, resolveApiBaseAtBuild, resolveApiBaseAtRuntime, apiConnectionErrorMessage, isApiConnectionError } from '../utils/resolve-api-base';
export { usePWA, useTransparentPwaIcon, useMaskablePwaIcon, useFaviconPwaIcon, useApplePwaIcon, useAppleSplashScreenPwaIcon } from '../node_modules/@vite-pwa/nuxt/dist/runtime/composables/index';