export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta } from '../node_modules/nuxt/dist/pages/runtime/composables';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useApiBase } from '../composables/useApiBase';
export { useAppToast } from '../composables/useAppToast';
export { useConfetti } from '../composables/useConfetti';
export { useConfirm } from '../composables/useConfirm';
export { useDietaProgress } from '../composables/useDietaProgress';
export { useFoodBank } from '../composables/useFoodBank';
export { useFoodSubstitution } from '../composables/useFoodSubstitution';
export { useMealItemOverrides } from '../composables/useMealItemOverrides';
export { useMealPlan } from '../composables/useMealPlan';
export { useMealSubstitutions } from '../composables/useMealSubstitutions';
export { usePatientApp, PatientProfile } from '../composables/usePatientApp';
export { usePatientAuth } from '../composables/usePatientAuth';
export { parseDocumentSrcQuery, resolveDocumentSrcFromRoute, normalizeDocumentUrl, usePatientDocument } from '../composables/usePatientDocument';
export { FOOD_WEEKDAYS, usePatientGoals, GoalFrequency, PatientGoal } from '../composables/usePatientGoals';
export { usePatientLocalTime } from '../composables/usePatientLocalTime';
export { usePatientMealPlan } from '../composables/usePatientMealPlan';
export { usePatientNavigationLoading } from '../composables/usePatientNavigationLoading';
export { formatNotificationTime, getNotificationGroup, mapNotificationItem, usePatientNotifications } from '../composables/usePatientNotifications';
export { usePatientOnboarding, PatientGender, PatientPrimaryGoal, PatientWorkoutsPerWeek, PatientProfileData, PatientProfileResponse } from '../composables/usePatientOnboarding';
export { usePatientTabBar } from '../composables/usePatientTabBar';
export { usePushNotifications } from '../composables/usePushNotifications';
export { useTileActionsMenu, closeAllTileActionMenus } from '../composables/useTileActionsMenu';
export { fetchUploadConfig, getCachedUploadConfig, formatDocumentMaxLabel, useDocumentUploadLimits } from '../composables/useUploadConfig';
export { getPatientScrollRoot, scrollPatientPageBy, lockPatientScroll, unlockPatientScroll, usePatientScrollLock, useVerticalWheelPassthrough, usePatientHorizontalWheelBridge } from '../composables/useVerticalWheelPassthrough';
export { useVideoUploadQueue } from '../composables/useVideoUploadQueue';
export { useVirtualKeyboard } from '../composables/useVirtualKeyboard';
export { useWeeklyCheckInPrompt } from '../composables/useWeeklyCheckInPrompt';
export { PROD_API_ORIGIN, PROD_API_BASE, PROD_WHATSAPP_API_BASE } from '../utils/api-env';
export { BELLA_ACTIONS, navigateBellaAction } from '../utils/bella-actions';
export { findRecentUserImageUrl, findLastUserQuestion, saveBellaChatHandoff, consumeBellaChatHandoff, buildChatHandoffFromMessages } from '../utils/bella-chat-handoff';
export { getMessageAttachment, getMessageDisplayText, shouldShowUserMessageText, getUserMessageImageUrl, formatBellaMarkdown } from '../utils/bella-message-format';
export { RESTAURANT_INTENT_OPTIONS, getRestaurantMessageMeta, hasActiveRestaurantIntent, findActiveRestaurantIntentMessage, getRestaurantIntentRelatedUserMessageId } from '../utils/bella-restaurant';
export { getSwapMessageMeta, hasActiveSwapSelection, hasActiveSwapMode, findActiveSwapMessage, getSwapOptions, isCompletedSwapMessage, findLatestCompletedSwapMessage } from '../utils/bella-swap';
export { getSeekFrameHeight, getChapterAtTime, buildSeekSpritePageUrl, getSeekThumbnailAtTime, buildSeekThumbnailStyle, buildSeekThumbnailImageStyle } from '../utils/bunny-seek-thumbnails';
export { isBunnyStreamVideoUrl, isBunnyStorageFileUrl, parseBunnyStreamVideoId, getBunnyStreamHlsUrl, getBunnyStreamCaptionUrl, getBunnyStreamCaptionCandidates, getBunnyStreamMp4Url } from '../utils/bunny-video';
export { formatCheckinAnswer, summarizeCheckinAnswers, buildAnswerRows, scoreFromTemplateAnswers, formatCheckinPeriod } from '../utils/checkin-answers';
export { CHECKIN_DEFAULT_STEPS } from '../utils/checkin-default-steps';
export { CHECKIN_STEP_TYPE_OPTIONS, defaultEditorStep, editorStepFromApi, buildStepPayload, buildStepPreviewPayload, normalizeFlowStep } from '../utils/checkin-step-schema';
export { fetchVideoUploadSignature, uploadVideoToCloudinary, uploadVideoToCloudinaryWithRetry } from '../utils/cloudinary-video-upload';
export { parseCloudinaryVideoUrl, getBaseCloudinaryVideoUrl, getCloudinaryCaptionUrl, isCloudinaryVideoUrl, applyCloudinaryVideoQuality, getCloudinaryHlsUrl, getQualityTargetHeight, parseTranscriptionTimeToSeconds, heightToQualityLabel, CloudinaryVideoRef, VideoQualityPreset } from '../utils/cloudinary-video';
export { isUuid, slugify, assignSlugs, getModuleSlug, findModuleBySlug, getLessonSlug, findLessonBySlug, buildModuleUrl } from '../utils/course-slug';
export { topicToTone, inferCourseTopic, countCourseLessons, formatModuleCount, formatLessonCount, mapCourseToTile, mapEbookToTile } from '../utils/course-tile';
export { fixWindowsVitePaths } from '../utils/fix-windows-vite-paths';
export { mapFoodItemFromApi, macrosForFoodRecord } from '../utils/food-bank';
export { formatNoteTime, loadLessonNotes, saveLessonNotes, createLessonNote, LessonNote } from '../utils/lesson-notes';
export { formatLessonSummaryHtml, hasLessonSummaryContent } from '../utils/lesson-summary-format';
export { getPatientTimeZone, getLocalDateKey, getLocalTimeParts, formatPatientDateLabel } from '../utils/local-date';
export { roundMacro, createMealItemId, createMealItem, normalizeItemFromAi, applyFoodMatch, scaleMealItem, isItemCounted, stripUncountedMacros, sumMealItems, normalizeMealItemsForSave, mealTypeLabel } from '../utils/meal-diary';
export { splitMealItemDisplay } from '../utils/meal-item-display';
export { formatMealItemLabel, formatMealItemsLabels } from '../utils/meal-plan-format';
export { parseMealTimeToMinutes, getMealIdForTimeFromMeals } from '../utils/meal-plan-time';
export { PORTION_MEASURES, looksLikeRecipe, guessGramsPerUnit, amountToGrams, gramsToAmount, formatMeasureHint, createPortionState } from '../utils/meal-portion-measures';
export { pickMealIcon, buildFallbackMealSlotOptions } from '../utils/meal-slot-options';
export { resolveTileCoverUrl } from '../utils/media-cover';
export { ensurePwaDevSwPlaceholder, mirrorPwaDevSwDist } from '../utils/mirror-pwa-dev-sw';
export { resolvePatientCoursePlayerUrl, openPatientCourse } from '../utils/open-patient-course';
export { isPatientAccessExpired, PATIENT_ACCESS_EXPIRED_MESSAGE, getFetchErrorMessage, isPatientAccessBlockedMessage, isPatientAccessBlockedError } from '../utils/patient-access';
export { toPdfByteArray, storePdfBytes } from '../utils/pdf-bytes';
export { phoneCountries, defaultPhoneCountry, digitsOnly, applyPhoneMask, formatNationalPhone, toInternationalPhone, parseInternationalPhone } from '../utils/phone-countries';
export { PWA_UPDATING_KEY, PWA_INSTALLED_KEY, isStandalonePwa, markPwaInstalled, isPwaInstalledPersisted, hasInstalledPwa, markPwaUpdating, clearPwaUpdating, isPwaUpdating, reloadPwaInPlace } from '../utils/pwa-standalone';
export { DEV_MOBILE_API_BASE, PROD_APP_HOSTNAMES, isLocalHostname, isPrivateLanHostname, isProdAppHostname, isPushSecureContext, resolveUploadApiUrl, resolveDirectApiUrl, normalizeUploadError, normalizeVideoUploadError, normalizeFileUploadError, resolveApiBaseAtBuild, resolveApiBaseAtRuntime, apiConnectionErrorMessage, sanitizeUserFacingError, isApiConnectionError } from '../utils/resolve-api-base';
export { parseVttToCaptionCues, getActiveCaptionCue, transcriptionToCaptionCues, getTranscriptionDisplayLines, formatTranscriptionDisplayTime, flattenTranscriptionChunks, getTranscriptionLineState, isTranscriptionChunkActive, CaptionCue, TranscriptionChunk } from '../utils/transcription';
export { EBOOK_PDF_MAX_BYTES, EBOOK_PDF_MAX_LABEL, EBOOK_PDF_UPLOAD_HINT, isPdfFile, isVideoFile } from '../utils/upload-file-kind';
export { isManagedVideoUrl, getVideoProvider, getVideoCaptionUrl, getVideoCaptionCandidates, shouldUseBackendVideoUpload } from '../utils/video-provider';
export { captureVideoThumbnail, revokeThumbnailUrl } from '../utils/video-thumbnail';
export { resolveVideoUploadEndpoint } from '../utils/video-upload-endpoint';
export { CLOUDINARY_VIDEO_MAX_BYTES, VIDEO_COMPRESS_THRESHOLD_BYTES, needsServerCompression, isCloudinarySizeError } from '../utils/video-upload-limits';
export { formatCloudinaryVideoPath, buildLessonLocationPath } from '../utils/video-upload-path';
export { usePWA, useTransparentPwaIcon, useMaskablePwaIcon, useFaviconPwaIcon, useApplePwaIcon, useAppleSplashScreenPwaIcon } from '../node_modules/@vite-pwa/nuxt/dist/runtime/composables/index';