import { StyleSheet } from 'react-native';
import { colors, fonts, radii, spacing } from '@/theme/tokens';

export const mealConfirmStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#fff',
  },
  screenEmbedded: {
    backgroundColor: 'transparent',
  },
  hero: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 0,
    elevation: 0,
    backgroundColor: colors.primaryDark,
    justifyContent: 'flex-end',
  },
  heroEmbedded: {
    backgroundColor: 'transparent',
  },
  heroImage: {
    ...StyleSheet.absoluteFillObject,
  },
  heroFallback: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.primaryDark,
  },
  heroScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(20,22,18,0.12)',
  },
  heroFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 150,
    backgroundColor: 'rgba(12,12,12,0.42)',
  },
  heroCopy: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 44,
    zIndex: 2,
    alignItems: 'center',
    paddingHorizontal: spacing[5],
    gap: 10,
  },
  healthPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(0,0,0,0.42)',
  },
  healthText: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: '#fff',
  },
  heroTitle: {
    fontFamily: fonts.bold,
    fontSize: 26,
    lineHeight: 30,
    letterSpacing: -0.5,
    color: '#fff',
    textAlign: 'center',
  },
  heroWhite: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#f3f3f3',
  },
  headerLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 8,
    elevation: 8,
    paddingBottom: 12,
  },
  scroll: {
    flex: 1,
    zIndex: 4,
    elevation: 4,
    backgroundColor: 'transparent',
  },
  heroBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing[4],
  },
  roundBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  roundBtnSpacer: {
    width: 36,
  },
  whenPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  whenText: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#fff',
  },
  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
  },
  handle: {
    alignSelf: 'center',
    width: 36,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#d8d8d8',
    marginTop: 10,
  },
  body: {
    paddingHorizontal: spacing[5],
    paddingTop: spacing[5],
    paddingBottom: spacing[6],
    gap: spacing[4],
  },
  sectionLabel: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: colors.textMuted,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    paddingBottom: spacing[3],
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  itemCopy: {
    flex: 1,
    gap: 3,
  },
  itemName: {
    fontFamily: fonts.semibold,
    fontSize: 16,
    color: colors.text,
  },
  itemMeta: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: colors.textMuted,
  },
  itemMacros: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 2,
  },
  itemMacro: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: colors.textMuted,
    marginRight: 8,
  },
  removeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: spacing[3],
  },
  addText: {
    fontFamily: fonts.semibold,
    fontSize: 15,
    color: colors.text,
  },
  hint: {
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 18,
    color: colors.textMuted,
    textAlign: 'center',
  },
  notes: {
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 18,
    color: colors.textMuted,
  },
  error: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: colors.error,
  },
  footer: {
    zIndex: 6,
    elevation: 6,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing[5],
    paddingTop: spacing[3],
    gap: 10,
    backgroundColor: '#fff',
  },
  correctBtn: {
    minHeight: 48,
    borderRadius: 18,
    backgroundColor: '#ececec',
    alignItems: 'center',
    justifyContent: 'center',
  },
  correctText: {
    fontFamily: fonts.semibold,
    fontSize: 15,
    color: colors.text,
  },
  confirmBtn: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: '#1a1a1a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmDisabled: {
    opacity: 0.55,
  },
  confirmText: {
    fontFamily: fonts.bold,
    fontSize: 16,
    color: '#fff',
  },
  bookmarkBtn: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: '#1a1a1a',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
