import { StyleSheet } from 'react-native';
import { colors, fonts, radii } from '@/theme/tokens';

export const mealDishEditStyles = StyleSheet.create({
  head: { alignItems: 'flex-end', marginBottom: 4 },
  close: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f2f2f7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontFamily: fonts.bold,
    fontSize: 26,
    color: colors.text,
    padding: 0,
  },
  hint: {
    marginTop: 4,
    marginBottom: 18,
    fontFamily: fonts.regular,
    fontSize: 14,
    color: colors.textMuted,
  },
  qtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
    marginBottom: 16,
  },
  segment: {
    flex: 1,
    flexDirection: 'row',
    padding: 3,
    borderRadius: radii.pill,
    backgroundColor: '#ececec',
  },
  segBtn: {
    flex: 1,
    minHeight: 34,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segOn: {
    backgroundColor: colors.text,
  },
  segText: {
    fontFamily: fonts.semibold,
    fontSize: 11,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: colors.textMuted,
  },
  segTextOn: { color: '#fff' },
  label: {
    fontFamily: fonts.semibold,
    fontSize: 16,
    color: colors.text,
  },
  boxWrap: {
    minWidth: 92,
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e5e5ea',
    borderRadius: radii.control,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
  },
  boxInput: {
    minWidth: 40,
    padding: 0,
    textAlign: 'center',
    fontFamily: fonts.medium,
    fontSize: 16,
    color: colors.text,
  },
  boxUnit: {
    marginLeft: 2,
    fontFamily: fonts.medium,
    fontSize: 16,
    color: colors.textMuted,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  box: {
    minWidth: 92,
    height: 44,
    borderWidth: 1,
    borderColor: '#e5e5ea',
    borderRadius: radii.control,
    paddingHorizontal: 12,
    textAlign: 'center',
    fontFamily: fonts.medium,
    fontSize: 16,
    color: colors.text,
    backgroundColor: '#fff',
  },
  boxMuted: {
    color: colors.textMuted,
    backgroundColor: '#fafafa',
  },
  toggleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    marginBottom: 16,
    borderRadius: radii.control,
    backgroundColor: '#f4f4f2',
  },
  toggleTitle: {
    fontFamily: fonts.semibold,
    fontSize: 14,
    color: colors.text,
  },
  toggleSub: {
    marginTop: 2,
    fontFamily: fonts.regular,
    fontSize: 12,
    color: colors.textMuted,
  },
  section: {
    marginBottom: 12,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: colors.textMuted,
    textTransform: 'uppercase',
  },
  macroName: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  save: {
    marginTop: 8,
    minHeight: 52,
    borderRadius: radii.control,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveText: {
    fontFamily: fonts.bold,
    fontSize: 16,
    color: '#fff',
  },
});
