
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  AppToast: typeof import("../../components/AppToast.vue")['default']
  CfConfirmModal: typeof import("../../components/CfConfirmModal.vue")['default']
  GoalMiniPie: typeof import("../../components/GoalMiniPie.vue")['default']
  PatientAvatar: typeof import("../../components/PatientAvatar.vue")['default']
  PatientBrandMark: typeof import("../../components/PatientBrandMark.vue")['default']
  PatientHeader: typeof import("../../components/PatientHeader.vue")['default']
  PatientLoadingLogo: typeof import("../../components/PatientLoadingLogo.vue")['default']
  PatientMealPlanGate: typeof import("../../components/PatientMealPlanGate.vue")['default']
  PatientMealPlanUploadOverlay: typeof import("../../components/PatientMealPlanUploadOverlay.vue")['default']
  PatientMenuDrawer: typeof import("../../components/PatientMenuDrawer.vue")['default']
  PatientNavigationLoader: typeof import("../../components/PatientNavigationLoader.vue")['default']
  PatientNotificationsPanel: typeof import("../../components/PatientNotificationsPanel.vue")['default']
  PatientPageSkeleton: typeof import("../../components/PatientPageSkeleton.vue")['default']
  PatientPdfViewer: typeof import("../../components/PatientPdfViewer.vue")['default']
  PatientPushSettings: typeof import("../../components/PatientPushSettings.vue")['default']
  PatientPwaPrompt: typeof import("../../components/PatientPwaPrompt.vue")['default']
  PatientPwaUpdate: typeof import("../../components/PatientPwaUpdate.vue")['default']
  PatientSkeleton: typeof import("../../components/PatientSkeleton.vue")['default']
  PatientTabBar: typeof import("../../components/PatientTabBar.vue")['default']
  PlayerHeader: typeof import("../../components/PlayerHeader.vue")['default']
  PlayerNavigation: typeof import("../../components/PlayerNavigation.vue")['default']
  BellaActionSheet: typeof import("../../components/bella/BellaActionSheet.vue")['default']
  BellaDailyDiaryBar: typeof import("../../components/bella/DailyDiaryBar.vue")['default']
  BellaFoodSearchPicker: typeof import("../../components/bella/FoodSearchPicker.vue")['default']
  BellaMealConfirmModal: typeof import("../../components/bella/MealConfirmModal.vue")['default']
  BellaMealPhotoGuideSheet: typeof import("../../components/bella/MealPhotoGuideSheet.vue")['default']
  BellaMealSlotPicker: typeof import("../../components/bella/MealSlotPicker.vue")['default']
  BellaPhotoGuideTipIcon: typeof import("../../components/bella/PhotoGuideTipIcon.vue")['default']
  BellaRestaurantIntentButtons: typeof import("../../components/bella/RestaurantIntentButtons.vue")['default']
  BellaSwapButtons: typeof import("../../components/bella/SwapButtons.vue")['default']
  BibliotecaScrollRow: typeof import("../../components/biblioteca/BibliotecaScrollRow.vue")['default']
  CheckinFridayPrompt: typeof import("../../components/checkin/CheckinFridayPrompt.vue")['default']
  CheckinTemplateEditorPreview: typeof import("../../components/checkin/CheckinTemplateEditorPreview.vue")['default']
  CheckinTypeformFlow: typeof import("../../components/checkin/CheckinTypeformFlow.vue")['default']
  CheckinFoodMoodPicker: typeof import("../../components/checkin/FoodMoodPicker.vue")['default']
  CheckinNotoEmojiLottie: typeof import("../../components/checkin/NotoEmojiLottie.client.vue")['default']
  CommunityFeed: typeof import("../../components/community/CommunityFeed.vue")['default']
  CoursesAulaPlayerIcons: typeof import("../../components/courses/AulaPlayerIcons.vue")['default']
  CoursesCourseVideoPlayer: typeof import("../../components/courses/CourseVideoPlayer.vue")['default']
  CoursesFlorescerPlayerIcons: typeof import("../../components/courses/FlorescerPlayerIcons.vue")['default']
  CoursesLessonFormModal: typeof import("../../components/courses/LessonFormModal.vue")['default']
  CoursesLessonNotesPanel: typeof import("../../components/courses/LessonNotesPanel.vue")['default']
  CoursesLessonSummaryContent: typeof import("../../components/courses/LessonSummaryContent.vue")['default']
  CoursesLessonSummaryPanel: typeof import("../../components/courses/LessonSummaryPanel.vue")['default']
  CoursesLessonTranscriptionPanel: typeof import("../../components/courses/LessonTranscriptionPanel.vue")['default']
  CoursesVideoUploadQueuePanel: typeof import("../../components/courses/VideoUploadQueuePanel.vue")['default']
  DietaCheckIcon: typeof import("../../components/dieta/CheckIcon.vue")['default']
  DietaMealPlanUploadCard: typeof import("../../components/dieta/MealPlanUploadCard.vue")['default']
  DietaMealSubstitutionsModal: typeof import("../../components/dieta/MealSubstitutionsModal.vue")['default']
  EvolucaoExerciseArm: typeof import("../../components/evolucao/ExerciseArm.vue")['default']
  EvolucaoFoodPlate: typeof import("../../components/evolucao/FoodPlate.vue")['default']
  EvolucaoGoalsPanel: typeof import("../../components/evolucao/GoalsPanel.vue")['default']
  EvolucaoNutritionMonthView: typeof import("../../components/evolucao/NutritionMonthView.vue")['default']
  EvolucaoSleepChart: typeof import("../../components/evolucao/SleepChart.vue")['default']
  EvolucaoWaterBottle: typeof import("../../components/evolucao/WaterBottle.vue")['default']
  EvolucaoWeightPanel: typeof import("../../components/evolucao/WeightPanel.vue")['default']
  HomeCurrentMealCard: typeof import("../../components/home/CurrentMealCard.vue")['default']
  HomeJourneyMacroRing: typeof import("../../components/home/JourneyMacroRing.vue")['default']
  HomeMacroBar: typeof import("../../components/home/MacroBar.vue")['default']
  HomeMacroPizzaRing: typeof import("../../components/home/MacroPizzaRing.vue")['default']
  HomeNutritionPanel: typeof import("../../components/home/NutritionPanel.vue")['default']
  HomeNutritionStatCarousel: typeof import("../../components/home/NutritionStatCarousel.vue")['default']
  OnboardingHeightPicker: typeof import("../../components/onboarding/OnboardingHeightPicker.vue")['default']
  OnboardingOptionCard: typeof import("../../components/onboarding/OnboardingOptionCard.vue")['default']
  OnboardingShell: typeof import("../../components/onboarding/OnboardingShell.vue")['default']
  PatientsPatientGoalsPanel: typeof import("../../components/patients/PatientGoalsPanel.vue")['default']
  PatientsPatientNutritionSection: typeof import("../../components/patients/PatientNutritionSection.vue")['default']
  PatientsPatientPhotosPanel: typeof import("../../components/patients/PatientPhotosPanel.vue")['default']
  SharedCfDateInput: typeof import("../../components/shared/CfDateInput.vue")['default']
  SharedCfDateTimeInput: typeof import("../../components/shared/CfDateTimeInput.vue")['default']
  SharedCfPhoneInput: typeof import("../../components/shared/CfPhoneInput.vue")['default']
  SharedCfSelect: typeof import("../../components/shared/CfSelect.vue")['default']
  SharedCfTileActionsMenu: typeof import("../../components/shared/CfTileActionsMenu.vue")['default']
  SharedCfTileCarousel: typeof import("../../components/shared/CfTileCarousel.vue")['default']
  SharedWeightRulerPicker: typeof import("../../components/shared/WeightRulerPicker.vue")['default']
  WhatsappBusinessProfileModal: typeof import("../../components/whatsapp/BusinessProfileModal.vue")['default']
  WhatsappChatBody: typeof import("../../components/whatsapp/ChatBody.vue")['default']
  WhatsappChatFooter: typeof import("../../components/whatsapp/ChatFooter.vue")['default']
  WhatsappChatHeader: typeof import("../../components/whatsapp/ChatHeader.vue")['default']
  WhatsappChatMessageActionsPanel: typeof import("../../components/whatsapp/ChatMessageActionsPanel.vue")['default']
  WhatsappChatSidebar: typeof import("../../components/whatsapp/ChatSidebar.vue")['default']
  WhatsappCreateGroupModal: typeof import("../../components/whatsapp/CreateGroupModal.vue")['default']
  WhatsappDocumentViewerModal: typeof import("../../components/whatsapp/DocumentViewerModal.vue")['default']
  WhatsappGroupInfoModal: typeof import("../../components/whatsapp/GroupInfoModal.vue")['default']
  WhatsappGroupMediaDocsModal: typeof import("../../components/whatsapp/GroupMediaDocsModal.vue")['default']
  WhatsappGroupMessageList: typeof import("../../components/whatsapp/GroupMessageList.vue")['default']
  WhatsappGroupPickerModal: typeof import("../../components/whatsapp/GroupPickerModal.vue")['default']
  WhatsappInteractiveButtonsBuilder: typeof import("../../components/whatsapp/InteractiveButtonsBuilder.vue")['default']
  WhatsappInteractiveCarouselBuilder: typeof import("../../components/whatsapp/InteractiveCarouselBuilder.vue")['default']
  WhatsappInteractiveListBuilder: typeof import("../../components/whatsapp/InteractiveListBuilder.vue")['default']
  WhatsappInteractiveMessagePreview: typeof import("../../components/whatsapp/InteractiveMessagePreview.vue")['default']
  WhatsappInteractivePreviewSideModal: typeof import("../../components/whatsapp/InteractivePreviewSideModal.vue")['default']
  WhatsappMediaComposerModal: typeof import("../../components/whatsapp/MediaComposerModal.vue")['default']
  WhatsappPollComposerModal: typeof import("../../components/whatsapp/PollComposerModal.vue")['default']
  WhatsappPrivateMessageList: typeof import("../../components/whatsapp/PrivateMessageList.vue")['default']
  WhatsappSaveContactModal: typeof import("../../components/whatsapp/SaveContactModal.vue")['default']
  WhatsappSendContactsModal: typeof import("../../components/whatsapp/SendContactsModal.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  VitePwaManifest: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
  NuxtPwaManifest: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
  NuxtPwaAssets: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
  PwaAppleImage: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
  PwaAppleSplashScreenImage: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
  PwaFaviconImage: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
  PwaMaskableImage: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
  PwaTransparentImage: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyAppToast: LazyComponent<typeof import("../../components/AppToast.vue")['default']>
  LazyCfConfirmModal: LazyComponent<typeof import("../../components/CfConfirmModal.vue")['default']>
  LazyGoalMiniPie: LazyComponent<typeof import("../../components/GoalMiniPie.vue")['default']>
  LazyPatientAvatar: LazyComponent<typeof import("../../components/PatientAvatar.vue")['default']>
  LazyPatientBrandMark: LazyComponent<typeof import("../../components/PatientBrandMark.vue")['default']>
  LazyPatientHeader: LazyComponent<typeof import("../../components/PatientHeader.vue")['default']>
  LazyPatientLoadingLogo: LazyComponent<typeof import("../../components/PatientLoadingLogo.vue")['default']>
  LazyPatientMealPlanGate: LazyComponent<typeof import("../../components/PatientMealPlanGate.vue")['default']>
  LazyPatientMealPlanUploadOverlay: LazyComponent<typeof import("../../components/PatientMealPlanUploadOverlay.vue")['default']>
  LazyPatientMenuDrawer: LazyComponent<typeof import("../../components/PatientMenuDrawer.vue")['default']>
  LazyPatientNavigationLoader: LazyComponent<typeof import("../../components/PatientNavigationLoader.vue")['default']>
  LazyPatientNotificationsPanel: LazyComponent<typeof import("../../components/PatientNotificationsPanel.vue")['default']>
  LazyPatientPageSkeleton: LazyComponent<typeof import("../../components/PatientPageSkeleton.vue")['default']>
  LazyPatientPdfViewer: LazyComponent<typeof import("../../components/PatientPdfViewer.vue")['default']>
  LazyPatientPushSettings: LazyComponent<typeof import("../../components/PatientPushSettings.vue")['default']>
  LazyPatientPwaPrompt: LazyComponent<typeof import("../../components/PatientPwaPrompt.vue")['default']>
  LazyPatientPwaUpdate: LazyComponent<typeof import("../../components/PatientPwaUpdate.vue")['default']>
  LazyPatientSkeleton: LazyComponent<typeof import("../../components/PatientSkeleton.vue")['default']>
  LazyPatientTabBar: LazyComponent<typeof import("../../components/PatientTabBar.vue")['default']>
  LazyPlayerHeader: LazyComponent<typeof import("../../components/PlayerHeader.vue")['default']>
  LazyPlayerNavigation: LazyComponent<typeof import("../../components/PlayerNavigation.vue")['default']>
  LazyBellaActionSheet: LazyComponent<typeof import("../../components/bella/BellaActionSheet.vue")['default']>
  LazyBellaDailyDiaryBar: LazyComponent<typeof import("../../components/bella/DailyDiaryBar.vue")['default']>
  LazyBellaFoodSearchPicker: LazyComponent<typeof import("../../components/bella/FoodSearchPicker.vue")['default']>
  LazyBellaMealConfirmModal: LazyComponent<typeof import("../../components/bella/MealConfirmModal.vue")['default']>
  LazyBellaMealPhotoGuideSheet: LazyComponent<typeof import("../../components/bella/MealPhotoGuideSheet.vue")['default']>
  LazyBellaMealSlotPicker: LazyComponent<typeof import("../../components/bella/MealSlotPicker.vue")['default']>
  LazyBellaPhotoGuideTipIcon: LazyComponent<typeof import("../../components/bella/PhotoGuideTipIcon.vue")['default']>
  LazyBellaRestaurantIntentButtons: LazyComponent<typeof import("../../components/bella/RestaurantIntentButtons.vue")['default']>
  LazyBellaSwapButtons: LazyComponent<typeof import("../../components/bella/SwapButtons.vue")['default']>
  LazyBibliotecaScrollRow: LazyComponent<typeof import("../../components/biblioteca/BibliotecaScrollRow.vue")['default']>
  LazyCheckinFridayPrompt: LazyComponent<typeof import("../../components/checkin/CheckinFridayPrompt.vue")['default']>
  LazyCheckinTemplateEditorPreview: LazyComponent<typeof import("../../components/checkin/CheckinTemplateEditorPreview.vue")['default']>
  LazyCheckinTypeformFlow: LazyComponent<typeof import("../../components/checkin/CheckinTypeformFlow.vue")['default']>
  LazyCheckinFoodMoodPicker: LazyComponent<typeof import("../../components/checkin/FoodMoodPicker.vue")['default']>
  LazyCheckinNotoEmojiLottie: LazyComponent<typeof import("../../components/checkin/NotoEmojiLottie.client.vue")['default']>
  LazyCommunityFeed: LazyComponent<typeof import("../../components/community/CommunityFeed.vue")['default']>
  LazyCoursesAulaPlayerIcons: LazyComponent<typeof import("../../components/courses/AulaPlayerIcons.vue")['default']>
  LazyCoursesCourseVideoPlayer: LazyComponent<typeof import("../../components/courses/CourseVideoPlayer.vue")['default']>
  LazyCoursesFlorescerPlayerIcons: LazyComponent<typeof import("../../components/courses/FlorescerPlayerIcons.vue")['default']>
  LazyCoursesLessonFormModal: LazyComponent<typeof import("../../components/courses/LessonFormModal.vue")['default']>
  LazyCoursesLessonNotesPanel: LazyComponent<typeof import("../../components/courses/LessonNotesPanel.vue")['default']>
  LazyCoursesLessonSummaryContent: LazyComponent<typeof import("../../components/courses/LessonSummaryContent.vue")['default']>
  LazyCoursesLessonSummaryPanel: LazyComponent<typeof import("../../components/courses/LessonSummaryPanel.vue")['default']>
  LazyCoursesLessonTranscriptionPanel: LazyComponent<typeof import("../../components/courses/LessonTranscriptionPanel.vue")['default']>
  LazyCoursesVideoUploadQueuePanel: LazyComponent<typeof import("../../components/courses/VideoUploadQueuePanel.vue")['default']>
  LazyDietaCheckIcon: LazyComponent<typeof import("../../components/dieta/CheckIcon.vue")['default']>
  LazyDietaMealPlanUploadCard: LazyComponent<typeof import("../../components/dieta/MealPlanUploadCard.vue")['default']>
  LazyDietaMealSubstitutionsModal: LazyComponent<typeof import("../../components/dieta/MealSubstitutionsModal.vue")['default']>
  LazyEvolucaoExerciseArm: LazyComponent<typeof import("../../components/evolucao/ExerciseArm.vue")['default']>
  LazyEvolucaoFoodPlate: LazyComponent<typeof import("../../components/evolucao/FoodPlate.vue")['default']>
  LazyEvolucaoGoalsPanel: LazyComponent<typeof import("../../components/evolucao/GoalsPanel.vue")['default']>
  LazyEvolucaoNutritionMonthView: LazyComponent<typeof import("../../components/evolucao/NutritionMonthView.vue")['default']>
  LazyEvolucaoSleepChart: LazyComponent<typeof import("../../components/evolucao/SleepChart.vue")['default']>
  LazyEvolucaoWaterBottle: LazyComponent<typeof import("../../components/evolucao/WaterBottle.vue")['default']>
  LazyEvolucaoWeightPanel: LazyComponent<typeof import("../../components/evolucao/WeightPanel.vue")['default']>
  LazyHomeCurrentMealCard: LazyComponent<typeof import("../../components/home/CurrentMealCard.vue")['default']>
  LazyHomeJourneyMacroRing: LazyComponent<typeof import("../../components/home/JourneyMacroRing.vue")['default']>
  LazyHomeMacroBar: LazyComponent<typeof import("../../components/home/MacroBar.vue")['default']>
  LazyHomeMacroPizzaRing: LazyComponent<typeof import("../../components/home/MacroPizzaRing.vue")['default']>
  LazyHomeNutritionPanel: LazyComponent<typeof import("../../components/home/NutritionPanel.vue")['default']>
  LazyHomeNutritionStatCarousel: LazyComponent<typeof import("../../components/home/NutritionStatCarousel.vue")['default']>
  LazyOnboardingHeightPicker: LazyComponent<typeof import("../../components/onboarding/OnboardingHeightPicker.vue")['default']>
  LazyOnboardingOptionCard: LazyComponent<typeof import("../../components/onboarding/OnboardingOptionCard.vue")['default']>
  LazyOnboardingShell: LazyComponent<typeof import("../../components/onboarding/OnboardingShell.vue")['default']>
  LazyPatientsPatientGoalsPanel: LazyComponent<typeof import("../../components/patients/PatientGoalsPanel.vue")['default']>
  LazyPatientsPatientNutritionSection: LazyComponent<typeof import("../../components/patients/PatientNutritionSection.vue")['default']>
  LazyPatientsPatientPhotosPanel: LazyComponent<typeof import("../../components/patients/PatientPhotosPanel.vue")['default']>
  LazySharedCfDateInput: LazyComponent<typeof import("../../components/shared/CfDateInput.vue")['default']>
  LazySharedCfDateTimeInput: LazyComponent<typeof import("../../components/shared/CfDateTimeInput.vue")['default']>
  LazySharedCfPhoneInput: LazyComponent<typeof import("../../components/shared/CfPhoneInput.vue")['default']>
  LazySharedCfSelect: LazyComponent<typeof import("../../components/shared/CfSelect.vue")['default']>
  LazySharedCfTileActionsMenu: LazyComponent<typeof import("../../components/shared/CfTileActionsMenu.vue")['default']>
  LazySharedCfTileCarousel: LazyComponent<typeof import("../../components/shared/CfTileCarousel.vue")['default']>
  LazySharedWeightRulerPicker: LazyComponent<typeof import("../../components/shared/WeightRulerPicker.vue")['default']>
  LazyWhatsappBusinessProfileModal: LazyComponent<typeof import("../../components/whatsapp/BusinessProfileModal.vue")['default']>
  LazyWhatsappChatBody: LazyComponent<typeof import("../../components/whatsapp/ChatBody.vue")['default']>
  LazyWhatsappChatFooter: LazyComponent<typeof import("../../components/whatsapp/ChatFooter.vue")['default']>
  LazyWhatsappChatHeader: LazyComponent<typeof import("../../components/whatsapp/ChatHeader.vue")['default']>
  LazyWhatsappChatMessageActionsPanel: LazyComponent<typeof import("../../components/whatsapp/ChatMessageActionsPanel.vue")['default']>
  LazyWhatsappChatSidebar: LazyComponent<typeof import("../../components/whatsapp/ChatSidebar.vue")['default']>
  LazyWhatsappCreateGroupModal: LazyComponent<typeof import("../../components/whatsapp/CreateGroupModal.vue")['default']>
  LazyWhatsappDocumentViewerModal: LazyComponent<typeof import("../../components/whatsapp/DocumentViewerModal.vue")['default']>
  LazyWhatsappGroupInfoModal: LazyComponent<typeof import("../../components/whatsapp/GroupInfoModal.vue")['default']>
  LazyWhatsappGroupMediaDocsModal: LazyComponent<typeof import("../../components/whatsapp/GroupMediaDocsModal.vue")['default']>
  LazyWhatsappGroupMessageList: LazyComponent<typeof import("../../components/whatsapp/GroupMessageList.vue")['default']>
  LazyWhatsappGroupPickerModal: LazyComponent<typeof import("../../components/whatsapp/GroupPickerModal.vue")['default']>
  LazyWhatsappInteractiveButtonsBuilder: LazyComponent<typeof import("../../components/whatsapp/InteractiveButtonsBuilder.vue")['default']>
  LazyWhatsappInteractiveCarouselBuilder: LazyComponent<typeof import("../../components/whatsapp/InteractiveCarouselBuilder.vue")['default']>
  LazyWhatsappInteractiveListBuilder: LazyComponent<typeof import("../../components/whatsapp/InteractiveListBuilder.vue")['default']>
  LazyWhatsappInteractiveMessagePreview: LazyComponent<typeof import("../../components/whatsapp/InteractiveMessagePreview.vue")['default']>
  LazyWhatsappInteractivePreviewSideModal: LazyComponent<typeof import("../../components/whatsapp/InteractivePreviewSideModal.vue")['default']>
  LazyWhatsappMediaComposerModal: LazyComponent<typeof import("../../components/whatsapp/MediaComposerModal.vue")['default']>
  LazyWhatsappPollComposerModal: LazyComponent<typeof import("../../components/whatsapp/PollComposerModal.vue")['default']>
  LazyWhatsappPrivateMessageList: LazyComponent<typeof import("../../components/whatsapp/PrivateMessageList.vue")['default']>
  LazyWhatsappSaveContactModal: LazyComponent<typeof import("../../components/whatsapp/SaveContactModal.vue")['default']>
  LazyWhatsappSendContactsModal: LazyComponent<typeof import("../../components/whatsapp/SendContactsModal.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyVitePwaManifest: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
  LazyNuxtPwaManifest: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
  LazyNuxtPwaAssets: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']>
  LazyPwaAppleImage: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']>
  LazyPwaAppleSplashScreenImage: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']>
  LazyPwaFaviconImage: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']>
  LazyPwaMaskableImage: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']>
  LazyPwaTransparentImage: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
